# Originally inspired by Cloudflare Wrangler
# https://github.com/cloudflare/wrangler2/blob/main/.github/workflows/prereleases.yml

name: Release - Beta

on:
  pull_request:
    branches:
      - main
jobs:
  prerelease:
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Modify package.json version
        run: node .github/version-script-beta.js

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc

      - name: Publish Beta to NPM
        run: npm run pub:beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-create-zcrm-widget@${{ steps.package-version.outputs.current-version }}-pr-${{ github.event.number }} # encode the PR number into the artifact name
          path: /dist/index.js
